import { AnimatePresence, motion } from "framer-motion";
import { Bell, Bookmark, CheckCircle2, Heart, MessageCircle, MoreHorizontal, Music2, Plus, Repeat2, Search, Send, Share2, Volume2, VolumeX, X } from "lucide-react";
import { useEffect, useRef, useState } from "react";
import BottomNav from "../../components/navigations/BottomNav";

const categories = ["For you", "Trending", "Friends", "Gaming", "Tech", "Music", "AI", "Fashion", "Sports"];
const stories = [
  ["Your story", "https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=160&q=80"],
  ["Maya", "https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=160&q=80"],
  ["Jordan", "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=160&q=80"],
  ["Aisha", "https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&w=160&q=80"],
  ["Kofi", "https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?auto=format&fit=crop&w=160&q=80"],
];
const initialPosts = [
  { id: 1, user: "Maya Okafor", handle: "@maya.builds", time: "2h", avatar: stories[1][1], image: "https://images.unsplash.com/photo-1519389950473-47ba0277781c?auto=format&fit=crop&w=1200&q=85", likes: 12500, comments: 1800, reposts: 742, caption: "Building my AI startup from Lagos, one late-night ship at a time. The future is feeling close. 🇳🇬", tags: "#AI #Startup #BuildInPublic", place: "Lagos, Nigeria", music: "Metro Boomin · Superhero" },
  { id: 2, user: "Noah Williams", handle: "@noahframes", time: "4h", avatar: stories[2][1], image: "https://images.unsplash.com/photo-1497366811353-6870744d04b2?auto=format&fit=crop&w=1200&q=85", likes: 8300, comments: 622, reposts: 284, caption: "A quiet corner for loud ideas. What are you creating this weekend?", tags: "#Design #CreativeLife #Studio", place: "Brooklyn, NY", music: "The xx · Intro" },
  { id: 3, user: "Sade Adeyemi", handle: "@sade.mp3", time: "6h", avatar: stories[3][1], image: "https://images.unsplash.com/photo-1506157786151-b8491531f063?auto=format&fit=crop&w=1200&q=85", likes: 21100, comments: 3100, reposts: 1900, caption: "This city moves to its own rhythm after midnight.", tags: "#Music #Live #Afrobeats", place: "London, UK", music: "Tems · Love Me JeJe" },
];
const comments = [
  ["Lara Mensah", "The energy in this is unreal ✨", "12m", "2.4K"],
  ["Tunde A.", "Proud of you, Maya. Keep going!", "9m", "856"],
  ["julescreates", "Need the full build log please 😭", "4m", "148"],
];
const compact = (n) => n >= 1000 ? `${(n / 1000).toFixed(n >= 10000 ? 1 : 1)}K` : n;

export default function Explore() {
  const [activeCategory, setActiveCategory] = useState("For you");
  const [posts, setPosts] = useState(initialPosts);
  const [activePost, setActivePost] = useState(null);
  const [liked, setLiked] = useState([]);
  const [saved, setSaved] = useState([]);
  const [muted, setMuted] = useState(true);
  const [heart, setHeart] = useState(false);
  const [sheet, setSheet] = useState(null);
  const [comment, setComment] = useState("");
  const [following, setFollowing] = useState(false);
  const loader = useRef(null);

  useEffect(() => {
    const observer = new IntersectionObserver(([entry]) => {
      if (entry.isIntersecting) setPosts((items) => items.length < 6 ? [...items, ...initialPosts.map((p, i) => ({ ...p, id: items.length + i + 10, time: "now" }))] : items);
    }, { rootMargin: "400px" });
    if (loader.current) observer.observe(loader.current);
    return () => observer.disconnect();
  }, []);

  const toggleLike = (id) => setLiked((ids) => ids.includes(id) ? ids.filter((item) => item !== id) : [...ids, id]);
  const doubleLike = (post) => { if (!liked.includes(post.id)) toggleLike(post.id); setHeart(true); window.setTimeout(() => setHeart(false), 750); };
  const share = async () => { if (navigator.share) { try { await navigator.share({ title: "ChatVerse", text: "Check this out on ChatVerse" }); } catch { /* cancelled */ } } else setSheet("share"); };

  return <main className="min-h-screen bg-[#09090b] pb-20 text-white selection:bg-fuchsia-500/50">
    <div className="pointer-events-none fixed inset-0 bg-[radial-gradient(circle_at_80%_-10%,rgba(124,58,237,.23),transparent_34%),radial-gradient(circle_at_10%_40%,rgba(217,70,239,.1),transparent_25%)]" />
    <div className="relative mx-auto max-w-[680px]">
      <header className="sticky top-0 z-30 border-b border-white/[.06] bg-[#09090b]/80 px-4 pb-3 pt-4 backdrop-blur-xl">
        <div className="flex items-center justify-between"><div className="flex items-center gap-2.5"><span className="grid h-9 w-9 place-items-center rounded-xl bg-gradient-to-br from-violet-500 to-fuchsia-500 text-lg font-black shadow-lg shadow-fuchsia-900/40">C</span><span className="font-['Space_Grotesk'] text-lg font-bold tracking-tight">ChatVerse</span></div><div className="flex items-center gap-1"><TopButton label="Search"><Search size={19}/></TopButton><TopButton label="Notifications"><Bell size={19}/></TopButton><button className="ml-1 grid h-9 w-9 place-items-center rounded-xl bg-gradient-to-br from-violet-600 to-fuchsia-500 shadow-lg shadow-fuchsia-900/30"><Plus size={20}/></button><img className="ml-2 h-9 w-9 rounded-xl object-cover ring-2 ring-fuchsia-500/60" src={stories[0][1]} /></div></div>
        <div className="mt-4 flex gap-2 overflow-x-auto pb-1 [scrollbar-width:none]">{categories.map((item) => <button onClick={() => setActiveCategory(item)} key={item} className={`shrink-0 rounded-full px-4 py-2 text-sm font-medium transition ${activeCategory === item ? "bg-gradient-to-r from-violet-600 to-fuchsia-600 text-white shadow-lg shadow-fuchsia-950/50" : "bg-white/[.055] text-zinc-400 hover:bg-white/10 hover:text-white"}`}>{item}</button>)}</div>
      </header>

      <section className="px-4 pt-5"><div className="mb-4 flex items-center gap-2"><span className="text-base">🔥</span><b className="font-['Space_Grotesk']">Trending Today</b><span className="h-px flex-1 bg-white/[.08]"/></div><div className="flex gap-2 overflow-x-auto [scrollbar-width:none]">{["#OpenAI", "#React19", "#Nigeria", "#PremierLeague", "#Photography"].map((tag, i) => <button className="shrink-0 rounded-xl border border-white/10 bg-white/[.045] px-3 py-2 text-sm text-zinc-300 transition hover:border-fuchsia-500/50 hover:text-white" key={tag}><span className="text-fuchsia-400">{i + 1} </span>{tag}</button>)}</div></section>
      <section className="px-4 pt-6"><div className="flex gap-4 overflow-x-auto [scrollbar-width:none]">{stories.map(([name, src], i) => <button key={name} className="group shrink-0" onClick={() => i && setActivePost({ story: true, user: name, image: src })}><div className={`rounded-full p-[2px] ${i ? "bg-gradient-to-tr from-fuchsia-500 via-violet-500 to-orange-400" : "bg-white/15"}`}><img className="h-15 w-15 h-[58px] w-[58px] rounded-full border-2 border-[#09090b] object-cover" src={src}/></div><span className="mt-1.5 block max-w-[62px] truncate text-xs text-zinc-400">{name}</span></button>)}</div></section>
      <section className="mx-4 mt-6 overflow-hidden rounded-[24px] border border-white/10 bg-gradient-to-br from-violet-900/55 via-[#18121f] to-fuchsia-950/45 p-4 shadow-xl shadow-black/20"><div className="flex items-center justify-between"><div><span className="rounded-md bg-red-500 px-2 py-1 text-[10px] font-bold tracking-wider">LIVE</span><h2 className="mt-3 font-['Space_Grotesk'] text-lg font-bold">Creators building in public</h2><p className="mt-1 text-sm text-zinc-400">2.8K watching now</p></div><button className="rounded-xl bg-white px-4 py-2.5 text-sm font-bold text-violet-700">Join live</button></div></section>
      <div className="mt-6 space-y-5 px-4">{posts.map((post) => <Post key={post.id} post={post} liked={liked.includes(post.id)} saved={saved.includes(post.id)} muted={muted} onLike={() => toggleLike(post.id)} onSave={() => setSaved((ids) => ids.includes(post.id) ? ids.filter((item) => item !== post.id) : [...ids, post.id])} onDouble={() => doubleLike(post)} onComment={() => { setActivePost(post); setSheet("comments"); }} onRepost={() => { setActivePost(post); setSheet("repost"); }} onShare={share} onMute={() => setMuted(!muted)} following={following} onFollow={() => setFollowing(!following)} heart={heart} />)}</div>
      <div ref={loader} className="flex justify-center py-8"><span className="h-6 w-6 animate-spin rounded-full border-2 border-fuchsia-400 border-t-transparent"/></div>
    </div>
    <BottomNav />
    <AnimatePresence>{activePost?.story && <motion.div initial={{opacity:0}} animate={{opacity:1}} exit={{opacity:0}} className="fixed inset-0 z-[60] grid place-items-center bg-black/90 p-4"><div className="relative h-[78vh] w-full max-w-md overflow-hidden rounded-[28px]"><img src={activePost.image} className="h-full w-full object-cover"/><div className="absolute inset-x-4 top-4 h-1 overflow-hidden rounded-full bg-white/30"><motion.i initial={{width:0}} animate={{width:"100%"}} transition={{duration:5}} className="block h-full bg-white"/></div><button onClick={() => setActivePost(null)} className="absolute right-4 top-8 rounded-full bg-black/30 p-2"><X size={20}/></button><b className="absolute bottom-5 left-5">{activePost.user}'s story</b></div></motion.div>}</AnimatePresence>
    <AnimatePresence>{sheet && <Sheet type={sheet} post={activePost} comment={comment} setComment={setComment} close={() => setSheet(null)} />}</AnimatePresence>
  </main>;
}

function TopButton({ children, label }) { return <button aria-label={label} className="grid h-9 w-9 place-items-center rounded-xl text-zinc-300 transition hover:bg-white/10 hover:text-white">{children}</button>; }
function Post({ post, liked, saved, muted, onLike, onSave, onDouble, onComment, onRepost, onShare, onMute, following, onFollow, heart }) { return <motion.article layout initial={{opacity:0,y:20}} animate={{opacity:1,y:0}} className="overflow-hidden rounded-[26px] border border-white/[.09] bg-[#131217] shadow-2xl shadow-black/30"><div className="flex items-center gap-3 px-4 pb-3 pt-4"><img src={post.avatar} className="h-10 w-10 rounded-full object-cover"/><div className="min-w-0 flex-1"><div className="flex items-center gap-1.5"><b className="truncate text-sm">{post.user}</b><CheckCircle2 size={15} className="fill-violet-500 text-white"/></div><span className="text-xs text-zinc-500">{post.handle} · {post.time}</span></div><button onClick={onFollow} className={`rounded-lg px-3 py-1.5 text-xs font-semibold ${following ? "bg-white/8 text-zinc-300" : "bg-violet-500/15 text-fuchsia-300"}`}>{following ? "Following" : "Follow"}</button><MoreHorizontal size={20} className="text-zinc-500"/></div><div onDoubleClick={onDouble} className="relative aspect-[4/5] cursor-pointer overflow-hidden bg-zinc-900"><img src={post.image} className="h-full w-full object-cover"/><div className="absolute inset-0 bg-gradient-to-t from-black/70 via-transparent to-black/10"/><AnimatePresence>{heart && <motion.div initial={{opacity:0,scale:.3}} animate={{opacity:1,scale:1}} exit={{opacity:0,scale:1.5}} className="absolute inset-0 grid place-items-center"><Heart className="fill-white text-white drop-shadow-2xl" size={105}/></motion.div>}</AnimatePresence><button onClick={onMute} className="absolute right-3 top-3 rounded-full bg-black/35 p-2 backdrop-blur"><>{muted ? <VolumeX size={17}/> : <Volume2 size={17}/>}</></button><div className="absolute bottom-0 left-0 right-0 p-4 pr-16"><p className="text-sm leading-5">{post.caption}</p><p className="mt-2 text-sm font-medium text-fuchsia-200">{post.tags}</p><div className="mt-2 flex items-center gap-2 text-xs text-zinc-300"><span>⌖ {post.place}</span></div><div className="mt-2 flex items-center gap-2 text-xs font-medium"><Music2 size={14}/><span>{post.music}</span></div></div><div className="absolute bottom-4 right-3 flex flex-col gap-3"><Action icon={<Heart fill={liked ? "currentColor" : "none"}/>} label={compact(post.likes + (liked ? 1 : 0))} active={liked} onClick={onLike}/><Action icon={<MessageCircle/>} label={compact(post.comments)} onClick={onComment}/><Action icon={<Repeat2/>} label={compact(post.reposts)} onClick={onRepost}/><Action icon={<Share2/>} label="Share" onClick={onShare}/><Action icon={<Bookmark fill={saved ? "currentColor" : "none"}/>} label={saved ? "Saved" : "Save"} active={saved} onClick={onSave}/></div></div></motion.article>; }
function Action({ icon, label, active, onClick }) { return <motion.button whileTap={{scale:.78}} onClick={onClick} className={`flex flex-col items-center gap-1 text-[11px] font-medium ${active ? "text-fuchsia-400" : "text-white"}`}>{icon}<span>{label}</span></motion.button>; }
function Sheet({ type, post, close, comment, setComment }) { const [reposted, setReposted] = useState(false); return <motion.div initial={{opacity:0}} animate={{opacity:1}} exit={{opacity:0}} className="fixed inset-0 z-50 flex items-end bg-black/65" onClick={close}><motion.section initial={{y:"100%"}} animate={{y:0}} exit={{y:"100%"}} transition={{type:"spring",damping:28,stiffness:280}} onClick={(e) => e.stopPropagation()} className="w-full rounded-t-[30px] border-t border-white/10 bg-[#16151b] px-5 pb-5 pt-3"><div className="mx-auto h-1.5 w-10 rounded-full bg-white/20"/><div className="mt-4 flex items-center justify-between"><h2 className="font-['Space_Grotesk'] text-lg font-bold">{type === "comments" ? `Comments · ${compact(post?.comments || 0)}` : type === "share" ? "Share to" : "Repost"}</h2><button onClick={close}><X className="text-zinc-400"/></button></div>{type === "comments" && <><div className="mt-4 max-h-[45vh] space-y-5 overflow-y-auto">{comments.map(([name, text, time, likes]) => <div className="flex gap-3" key={name}><span className="grid h-9 w-9 shrink-0 place-items-center rounded-full bg-gradient-to-br from-violet-500 to-fuchsia-500 text-xs font-bold">{name[0]}</span><div className="flex-1"><b className="text-sm">{name}</b><p className="mt-0.5 text-sm text-zinc-300">{text}</p><div className="mt-2 flex gap-4 text-xs text-zinc-500"><span>{time}</span><span>Reply</span><span>♡ {likes}</span></div></div></div>)}</div><div className="mt-4 flex gap-2 border-t border-white/10 pt-4"><button className="text-xl">😊</button><input value={comment} onChange={(e) => setComment(e.target.value)} placeholder="Add a comment… @mention" className="min-w-0 flex-1 bg-transparent text-sm outline-none placeholder:text-zinc-500"/><button className="rounded-xl bg-gradient-to-r from-violet-600 to-fuchsia-600 p-2"><Send size={16}/></button></div></>}{type === "repost" && <div className="mt-5 space-y-2"><button onClick={() => setReposted(!reposted)} className="flex w-full items-center gap-3 rounded-2xl bg-white/[.06] p-4 text-left"><Repeat2 className="text-fuchsia-400"/><span>{reposted ? "Undo repost" : "Repost"}</span></button><button className="flex w-full items-center gap-3 rounded-2xl bg-white/[.06] p-4 text-left"><MessageCircle className="text-fuchsia-400"/><span>Quote post</span></button></div>}{type === "share" && <div className="mt-5 grid grid-cols-4 gap-4">{["Friends", "Copy link", "WhatsApp", "Telegram", "Facebook", "X", "Instagram", "Download"].map((item, i) => <button key={item} className="flex flex-col items-center gap-2 text-xs text-zinc-300"><span className="grid h-12 w-12 place-items-center rounded-2xl bg-gradient-to-br from-white/12 to-white/[.04] text-lg">{["✦","↗","◉","➤","f","𝕏","◎","↓"][i]}</span>{item}</button>)}</div>}</motion.section></motion.div>; }
