import { Bell, Bot, CalendarDays, ChevronRight, CirclePlay, Compass, FileText, Forward, Hash, Heart, MessageCircle, Mic, Plus, Repeat2, Search, Sparkles, Users } from "lucide-react";
import { useEffect, useState } from "react";
import BottomNav from "../../components/navigations/BottomNav";
import { toast } from "react-toastify";
import { askExploreAi, createExplorePost, getExploreData } from "../../services/chatService";
import socket from "../../lib/socket";

const categories = ["Trending", "Communities", "AI", "Gaming", "Technology", "Music", "Sports", "Business", "Education", "Design"];
const chats = [
  ["Design After Dark", "2.4k active", "The future of product design", "DA"],
  ["React Builders", "1.8k active", "Ship better interfaces together", "⚛"],
  ["The Startup Circle", "986 active", "Ideas, founders & funding", "SC"],
];
const assistants = [["✦", "ChatVerse AI", "Your always-on creative partner"], ["</>", "Coding Assistant", "Debug, build and learn faster"], ["✎", "Study Assistant", "Turn lessons into breakthroughs"], ["↗", "Business Advisor", "Strategy for your next move"], ["✈", "Travel Planner", "Thoughtful trips, beautifully planned"]];
const people = [["M", "Maya Thompson", "12 mutual friends"], ["J", "Jordan Lee", "8 mutual friends"], ["A", "Amara Okafor", "6 mutual friends"]];

const Avatar = ({ value, className = "" }) => <span className={`flex shrink-0 items-center justify-center rounded-2xl bg-gradient-to-br from-violet-500 to-fuchsia-500 font-semibold text-white shadow-lg shadow-fuchsia-950/40 ${className}`}>{value}</span>;

export default function Explore() {
  const [active, setActive] = useState("Trending");
  const [following, setFollowing] = useState([]);
  const [visible, setVisible] = useState(3);
  const [loading, setLoading] = useState(true);
  const [liked, setLiked] = useState([]);
  const [joined, setJoined] = useState([]);
  const [live, setLive] = useState({ communities: [], people: [], posts: [] });
  const [aiPost, setAiPost] = useState(null);
  const [aiQuestion, setAiQuestion] = useState("");
  const [aiAnswer, setAiAnswer] = useState("");
  const [askingAi, setAskingAi] = useState(false);
  const [composerOpen, setComposerOpen] = useState(false);
  const [draft, setDraft] = useState("");
  const [postType, setPostType] = useState("Post");
  useEffect(() => { const id = setTimeout(() => setLoading(false), 500); return () => clearTimeout(id); }, []);
  useEffect(() => {
    let mounted = true;
    const load = () => getExploreData().then((data) => mounted && setLive(data)).catch(() => {});
    load();
    socket.on("newMessage", load);
    socket.on("messageUpdated", load);
    return () => { mounted = false; socket.off("newMessage", load); socket.off("messageUpdated", load); };
  }, []);
  useEffect(() => {
    const loadMore = () => { if (window.innerHeight + window.scrollY > document.body.offsetHeight - 450) setVisible((n) => Math.min(n + 2, chats.length)); };
    window.addEventListener("scroll", loadMore, { passive: true }); return () => window.removeEventListener("scroll", loadMore);
  }, []);
  const toggleFollow = (name) => setFollowing((items) => items.includes(name) ? items.filter((item) => item !== name) : [...items, name]);
  const notify = (message) => toast.success(message);
  const askAi = async () => { try { setAskingAi(true); const data = await askExploreAi(aiPost, aiQuestion); setAiAnswer(data.answer); } catch (error) { setAiAnswer(error.response?.data?.message || "AI could not respond right now."); } finally { setAskingAi(false); } };
  const publishPost = async () => { try { const post = await createExplorePost({ text: draft, type: postType }); setLive((data) => ({ ...data, posts: [post, ...data.posts] })); setDraft(""); setComposerOpen(false); toast.success("Post published"); } catch (error) { toast.error(error.response?.data?.message || "Could not publish post"); } };
  const feedPosts = live.posts.map((post) => ({ type: post.type, icon: "✦", author: post.author?.name || "ChatVerse member", initials: post.author?.name?.slice(0, 2).toUpperCase() || "CV", community: "ChatVerse", text: post.text, likes: post.likes?.length || 0, visual: post.mediaUrl ? "from-violet-700 via-fuchsia-600 to-rose-400" : "" }));

  return <main className="min-h-screen overflow-x-hidden bg-[#09090b] pb-28 font-sans text-white selection:bg-fuchsia-500/40">
    <div className="pointer-events-none fixed inset-x-0 top-0 h-80 bg-[radial-gradient(ellipse_at_top,_rgba(124,58,237,.24),transparent_65%)]" />
    <div className="relative mx-auto max-w-2xl px-4 pt-6 sm:px-6">
      <header className="mb-6 flex items-center justify-between"><div><p className="text-xs font-medium uppercase tracking-[.2em] text-fuchsia-300">Discover</p><h1 className="mt-1 font-['Space_Grotesk'] text-3xl font-bold tracking-tight">Explore ChatVerse</h1></div><button className="glass flex h-11 w-11 items-center justify-center rounded-2xl text-zinc-300 transition hover:scale-105 hover:text-white"><Bell size={19} /></button></header>
      <label className="glass group flex items-center gap-3 rounded-[20px] px-4 py-4 shadow-2xl shadow-black/20"><Search size={20} className="text-fuchsia-300 transition group-focus-within:scale-110" /><input className="min-w-0 flex-1 bg-transparent text-sm outline-none placeholder:text-zinc-500" placeholder="Search people, groups, AI..." /></label>

      <div className="-mx-4 mt-5 flex gap-2 overflow-x-auto px-4 pb-2 [scrollbar-width:none]">{categories.map((category) => <button key={category} onClick={() => setActive(category)} className={`shrink-0 rounded-full px-4 py-2 text-sm font-medium transition active:scale-95 ${active === category ? "bg-gradient-to-r from-violet-600 to-fuchsia-600 shadow-lg shadow-fuchsia-900/35" : "glass text-zinc-400 hover:text-white"}`}>{category}</button>)}</div>

      {loading ? <div className="mt-6 h-64 animate-pulse rounded-[24px] bg-zinc-800/60" /> : <section className="relative mt-6 overflow-hidden rounded-[24px] border border-white/10 bg-zinc-900/75 p-5 shadow-2xl shadow-black/30 backdrop-blur-xl"><div className="absolute inset-0 bg-[radial-gradient(circle_at_85%_10%,rgba(217,70,239,.45),transparent_33%),linear-gradient(135deg,rgba(124,58,237,.45),transparent_65%)]" /><div className="relative"><span className="inline-flex items-center gap-1 rounded-full bg-white/15 px-3 py-1 text-xs font-medium text-fuchsia-100"><Sparkles size={13} /> Featured community</span><div className="mt-10 flex items-end justify-between"><div className="min-w-0"><Avatar value="◈" className="mb-3 h-12 w-12 text-xl" /><h2 className="font-['Space_Grotesk'] text-2xl font-bold">Future Makers</h2><p className="mt-1 text-sm text-violet-100">24.8k members · Building what’s next</p></div><button className="rounded-xl bg-white px-4 py-2.5 text-sm font-bold text-violet-700 transition hover:scale-105 active:scale-95">Join</button></div><p className="mt-4 max-w-md text-sm leading-6 text-violet-100/90">A curated home for builders, designers and curious minds shaping tomorrow.</p></div></section>}

      <Section title="From the community" action="See feed"><div className="-mx-4 flex gap-2 overflow-x-auto px-4 pb-2 [scrollbar-width:none]">{["All", "📸 Photos", "🎥 Videos", "🎙 Voice", "📝 Articles", "📊 Polls", "📅 Events", "💼 Jobs", "🤖 AI"].map((label) => <button key={label} className="glass shrink-0 rounded-full px-3 py-1.5 text-xs text-zinc-300 transition hover:text-fuchsia-300">{label}</button>)}</div>{feedPosts.length ? feedPosts.map((post, index) => <PostCard key={`${post.author}-${post.type}-${index}`} post={post} liked={liked.includes(post.author)} joined={joined.includes(post.author)} onLike={() => setLiked((items) => items.includes(post.author) ? items.filter((name) => name !== post.author) : [...items, post.author])} onJoin={() => setJoined((items) => items.includes(post.author) ? items.filter((name) => name !== post.author) : [...items, post.author])} onAskAi={() => { setAiPost(post); setAiQuestion(""); setAiAnswer(""); }} notify={notify} />) : <div className="glass mt-4 rounded-[22px] p-7 text-center"><Sparkles className="mx-auto text-fuchsia-400" /><h3 className="mt-3 font-semibold">Nothing shared yet</h3><p className="mt-1 text-sm text-zinc-400">Be the first to post something for the community.</p><button onClick={() => setComposerOpen(true)} className="mt-4 rounded-xl bg-gradient-to-r from-violet-600 to-fuchsia-600 px-4 py-2 text-sm font-semibold">Create post</button></div>}</Section>

      <Section title="Trending chats" action="See all">{(live.communities.length ? live.communities.map((group) => [group.groupName || "Group chat", `${group.participants?.length || 0} members`, "Live community", group.groupName?.slice(0, 2) || "CV"]) : chats).slice(0, visible).map(([name, activeUsers, topic, avatar]) => <article key={name} className="glass card-rise mb-3 flex items-center gap-3 rounded-[20px] p-3"><Avatar value={avatar} className="h-12 w-12" /><div className="min-w-0 flex-1"><h3 className="truncate font-semibold">{name}</h3><p className="mt-0.5 text-xs text-emerald-300">● {activeUsers}</p><p className="truncate text-xs text-zinc-500">{topic}</p></div><button className="rounded-xl bg-violet-500/15 px-3 py-2 text-xs font-semibold text-fuchsia-300 transition hover:bg-fuchsia-500 hover:text-white">Join</button></article>)}</Section>
      <Section title="Popular AI assistants" action="View all"><div className="-mx-4 flex gap-3 overflow-x-auto px-4 pb-2 [scrollbar-width:none]">{assistants.map(([icon, name, description]) => <article key={name} className="glass card-rise w-44 shrink-0 rounded-[20px] p-4"><Avatar value={icon} className="h-11 w-11 text-sm" /><h3 className="mt-4 font-semibold">{name}</h3><p className="mt-1 h-10 text-xs leading-5 text-zinc-400">{description}</p><button className="mt-4 w-full rounded-xl bg-white/8 py-2 text-xs font-semibold text-fuchsia-300 transition hover:bg-fuchsia-500 hover:text-white">Chat</button></article>)}</div></Section>
      <Section title="Suggested for you" action="Refresh">{(live.people.length ? live.people.map((person) => [person.name?.charAt(0) || "?", person.name, person.bio || "New on ChatVerse"]) : people).slice(0, 5).map(([avatar, name, mutual]) => <article key={name} className="glass card-rise mb-3 flex items-center gap-3 rounded-[20px] p-3"><Avatar value={avatar} className="h-12 w-12" /><div className="flex-1"><h3 className="font-semibold">{name}</h3><p className="text-xs text-zinc-500">{mutual}</p></div><button onClick={() => toggleFollow(name)} className={`rounded-xl px-3 py-2 text-xs font-semibold transition ${following.includes(name) ? "bg-white/10 text-zinc-300" : "bg-gradient-to-r from-violet-600 to-fuchsia-600"}`}>{following.includes(name) ? "Following" : "Follow"}</button></article>)}</Section>
      <Section title="Trending now"><div className="grid grid-cols-2 gap-3">{["AI", "React", "JavaScript", "Football", "Crypto", "Music", "Startup", "Design"].map((tag, index) => <button key={tag} className="glass card-rise rounded-2xl p-4 text-left"><Hash className="mb-3 text-fuchsia-400" size={18} /><b>#{tag}</b><span className="mt-1 block text-xs text-zinc-500">{(12.4 - index * .8).toFixed(1)}k conversations</span></button>)}</div></Section>
      <Section title="Upcoming events" action="Calendar"><div className="-mx-4 flex gap-3 overflow-x-auto px-4 pb-2 [scrollbar-width:none]">{[["Creator Camp", "AUG 18 · 6:00 PM", "1.2k interested"], ["AI Design Jam", "AUG 24 · 2:00 PM", "846 interested"]].map(([name, date, interested], index) => <article key={name} className="glass card-rise w-64 shrink-0 overflow-hidden rounded-[20px]"><div className={`h-24 bg-gradient-to-br ${index ? "from-fuchsia-600 to-orange-400" : "from-indigo-600 to-fuchsia-500"}`}><CalendarDays className="m-4 text-white/70" /></div><div className="p-4"><h3 className="font-semibold">{name}</h3><p className="mt-1 text-xs text-fuchsia-300">{date}</p><p className="mt-1 text-xs text-zinc-500">{interested}</p><button className="mt-4 w-full rounded-xl bg-white/10 py-2 text-xs font-semibold hover:bg-white/20">RSVP</button></div></article>)}</div></Section>
      <Section title="Recommended channels"><div className="grid gap-3 sm:grid-cols-2">{[["◉", "Tech Pulse", "84k subscribers"], ["♫", "Midnight Radio", "56k subscribers"], ["▣", "Design Daily", "39k subscribers"]].map(([logo, name, subscribers]) => <article key={name} className="glass card-rise flex items-center gap-3 rounded-[20px] p-3"><Avatar value={logo} className="h-11 w-11" /><div className="min-w-0 flex-1"><b className="block truncate text-sm">{name}</b><small className="text-zinc-500">{subscribers}</small></div><ChevronRight size={17} className="text-zinc-500" /></article>)}</div></Section>
    </div>
    <button onClick={() => setComposerOpen(true)} className="fixed bottom-20 right-5 z-40 flex h-14 w-14 items-center justify-center rounded-2xl bg-gradient-to-br from-violet-600 to-fuchsia-600 shadow-xl shadow-fuchsia-900/50 transition hover:scale-110 active:scale-95" aria-label="Create"><Plus size={25} /></button>
    <BottomNav />
    {aiPost && <div className="fixed inset-0 z-[70] flex items-end bg-black/70 p-4 sm:items-center sm:justify-center"><section className="glass w-full max-w-md rounded-[24px] p-5"><div className="flex items-center justify-between"><h2 className="font-['Space_Grotesk'] text-lg font-bold">Ask ChatVerse AI</h2><button onClick={() => setAiPost(null)} className="text-zinc-400">×</button></div><p className="mt-2 text-sm text-zinc-400">About: {aiPost.text}</p><textarea value={aiQuestion} onChange={(event) => setAiQuestion(event.target.value)} placeholder="What would you like to know?" className="mt-4 w-full rounded-xl bg-white/7 p-3 text-sm outline-none placeholder:text-zinc-500" rows="3" /><button disabled={askingAi} onClick={askAi} className="mt-3 w-full rounded-xl bg-gradient-to-r from-violet-600 to-fuchsia-600 py-3 text-sm font-semibold disabled:opacity-50">{askingAi ? "Thinking…" : "Ask AI"}</button>{aiAnswer && <p className="mt-4 whitespace-pre-wrap rounded-xl bg-white/6 p-3 text-sm leading-6 text-zinc-200">{aiAnswer}</p>}</section></div>}
    {composerOpen && <div className="fixed inset-0 z-[70] flex items-end bg-black/70 p-4 sm:items-center sm:justify-center"><section className="glass w-full max-w-md rounded-[24px] p-5"><div className="flex items-center justify-between"><h2 className="font-['Space_Grotesk'] text-lg font-bold">Create post</h2><button onClick={() => setComposerOpen(false)} className="text-zinc-400">×</button></div><select value={postType} onChange={(event) => setPostType(event.target.value)} className="mt-4 rounded-xl bg-white/8 px-3 py-2 text-sm outline-none"><option>Post</option><option>Photo</option><option>Video</option><option>Voice post</option><option>Article</option><option>Poll</option><option>Event</option><option>Job post</option><option>AI generated</option></select><textarea value={draft} onChange={(event) => setDraft(event.target.value)} placeholder="What do you want to share?" className="mt-3 w-full rounded-xl bg-white/7 p-3 text-sm outline-none placeholder:text-zinc-500" rows="5" /><button disabled={!draft.trim()} onClick={publishPost} className="mt-3 w-full rounded-xl bg-gradient-to-r from-violet-600 to-fuchsia-600 py-3 text-sm font-semibold disabled:opacity-50">Publish post</button></section></div>}
  </main>;
}

function Section({ title, action, children }) { return <section className="mt-9"><div className="mb-3 flex items-center justify-between"><h2 className="font-['Space_Grotesk'] text-lg font-bold">{title}</h2>{action && <button className="text-xs font-medium text-fuchsia-300">{action}</button>}</div>{children}</section>; }

function PostCard({ post, liked, joined, onLike, onJoin, onAskAi, notify }) {
  const count = post.likes + (liked ? 1 : 0);
  return <article className="glass card-rise mt-4 overflow-hidden rounded-[22px] p-4">
    <div className="flex items-center gap-3"><Avatar value={post.initials} className="h-10 w-10 text-xs" /><div className="min-w-0 flex-1"><b className="block text-sm">{post.author}</b><span className="text-xs text-zinc-500">{post.community}</span></div><span className="rounded-full bg-fuchsia-500/10 px-2.5 py-1 text-[11px] font-medium text-fuchsia-300">{post.icon} {post.type}</span></div>
    <p className="mt-4 text-sm leading-6 text-zinc-200">{post.text}</p>
    {post.visual && <div className={`relative mt-4 flex h-40 items-end overflow-hidden rounded-2xl bg-gradient-to-br ${post.visual} p-4`}><div className="absolute inset-0 bg-[radial-gradient(circle_at_80%_15%,rgba(255,255,255,.3),transparent_25%)]" />{post.video && <span className="relative flex h-11 w-11 items-center justify-center rounded-full bg-white/20 backdrop-blur"><CirclePlay /></span>}<span className="relative ml-auto text-xs text-white/80">{post.type === "AI generated" ? "Generated with ChatVerse AI" : "Tap to view"}</span></div>}
    {post.audio && <button onClick={() => notify("Playing voice post")} className="mt-4 flex w-full items-center gap-3 rounded-2xl bg-white/5 p-3 text-left"><span className="flex h-9 w-9 items-center justify-center rounded-full bg-fuchsia-500"><Mic size={16} /></span><span className="flex-1"><b className="block text-xs">0:45 voice post</b><span className="text-xs text-zinc-500">Tap to play</span></span><span className="h-1.5 w-20 rounded-full bg-gradient-to-r from-fuchsia-500 to-violet-500" /></button>}
    {post.article && <button onClick={() => notify("Opening article")} className="mt-4 flex w-full items-center gap-3 rounded-2xl bg-violet-500/10 p-3 text-left"><FileText className="text-fuchsia-300" /><span><b className="block text-sm">Read full article</b><span className="text-xs text-zinc-400">6 min read</span></span></button>}
    {post.poll && <div className="mt-4 space-y-2">{post.poll.map((option, index) => <button key={option} onClick={() => notify(`Voted for ${option}`)} className="relative w-full overflow-hidden rounded-xl border border-white/10 px-3 py-2.5 text-left text-xs"><span className="absolute inset-y-0 left-0 bg-fuchsia-500/15" style={{ width: `${58 - index * 13}%` }} /><span className="relative">{option}</span></button>)}</div>}
    {(post.event || post.job) && <button onClick={() => notify(post.event ? "You’re interested in this event" : "Application details opened")} className="mt-4 w-full rounded-xl bg-white/8 py-2.5 text-sm font-semibold text-fuchsia-200">{post.event ? "RSVP" : "View role"}</button>}
    <div className="mt-4 flex items-center gap-1 border-t border-white/8 pt-3 text-zinc-400"><Action icon={<Heart size={17} fill={liked ? "currentColor" : "none"} />} label={count} active={liked} onClick={onLike} /><Action icon={<MessageCircle size={17} />} label="Comment" onClick={() => notify("Comments opened")} /><Action icon={<Repeat2 size={17} />} label="Repost" onClick={() => notify("Post reposted")} /><Action icon={<Forward size={17} />} label="Forward" onClick={() => notify("Choose a chat to forward this post")} /></div>
    <div className="mt-3 grid grid-cols-2 gap-2"><button onClick={() => notify(`Starting a chat with ${post.author}`)} className="rounded-xl bg-white/7 py-2 text-xs font-medium hover:bg-white/12">💬 Start Chat</button><button onClick={onJoin} className="rounded-xl bg-gradient-to-r from-violet-600/85 to-fuchsia-600/85 py-2 text-xs font-semibold">{joined ? "✓ Joined" : "👥 Join Community"}</button><button onClick={() => notify("Following channel")} className="rounded-xl bg-white/7 py-2 text-xs font-medium hover:bg-white/12">🔔 Follow Channel</button><button onClick={onAskAi} className="rounded-xl bg-white/7 py-2 text-xs font-medium hover:bg-white/12">🤖 Ask AI</button></div>
  </article>;
}
function Action({ icon, label, active, onClick }) { return <button onClick={onClick} className={`flex flex-1 items-center justify-center gap-1 rounded-lg py-2 text-xs transition hover:bg-white/8 ${active ? "text-fuchsia-400" : ""}`}>{icon}<span>{label}</span></button>; }
